<a href="https://colab.research.google.com/github/AbbasAli01/AbbasAli/blob/main/NumPy_Crash_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1) Creating NumPy array From a Python list

In [ ]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
l = [1, 2, 3, 4, 5]

arr = np.array(l)
arr

# Output: array([1, 2, 3, 4])

array([1, 2, 3, 4, 5])

# 2) NumPy Datatypes

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr1.dtype

dtype('int64')

In [ ]:
arr1 = np.array([1, 2, 3, 4], dtype='int32')
arr1.dtype

dtype('int32')

In [ ]:
arr2 = np.array(['a', 'b', 'c', 'd'])
arr2.dtype

dtype('<U1')

In [ ]:
arr2 = np.array(['apple', 'banana', 'cherry', 'dragon', 'Hello World!'])
arr2.dtype

dtype('<U12')

In [ ]:
arr1 = np.array([1, 2, 3, 4], dtype=str)
arr1.dtype

dtype('<U1')

In [ ]:
arr3 = np.array([1.2, 2.3, 3.4, 4.5])
arr3.dtype

dtype('float64')

In [ ]:
arr4 = np.array([True, False, True, False])
arr4.dtype

dtype('bool')

# 3) Creating arrays of different dimensions

In [ ]:
d0 = np.array(6)
d0, d0.ndim

(array(6), 0)

In [ ]:
d1 = np.array([1, 2, 3, 4])
d1, d1.ndim

(array([1, 2, 3, 4]), 1)

In [ ]:
d2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8]])
d2, d2.ndim

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 2)

In [ ]:
d3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
               [10, 11, 12]]])
d3, d3.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 3)

In [ ]:
d4 = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
                [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
d4, d4.ndim

(array([[[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]]],
 
 
        [[[ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16]]]]),
 4)

# 4) Attributes of NumPy array

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array(['a', 'b', 'c', 'd'])
arr3 = np.array([1.1, 2.2, 3.3, 4.4])
arr4 = np.array([True, False, True, False])
arr1.dtype, arr2.dtype, arr3.dtype, arr4.dtype

(dtype('int64'), dtype('<U1'), dtype('float64'), dtype('bool'))

In [ ]:
arr4 = np.array([1, 2, 3, 4])
arr5 = np.array([[1, 2, 3], [4, 5, 6]])
arr6 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr4.ndim, arr5.ndim, arr6.ndim

(1, 2, 3)

In [ ]:
arr4.shape, arr5.shape, arr6.shape

((4,), (2, 3), (2, 2, 3))

In [ ]:
arr4.size, arr5.size, arr6.size

(4, 6, 12)

In [ ]:
arr4.itemsize, arr5.itemsize, arr6.itemsize

(8, 8, 8)

In [ ]:
arr4 = np.array([1, 2, 3, 4], dtype='int32')

In [ ]:
arr4.itemsize, arr5.itemsize, arr6.itemsize

(4, 8, 8)

In [ ]:
arr4.nbytes, arr5.nbytes, arr6.nbytes

(16, 48, 96)

# 5) Creating arrays using NumPy functions

In [ ]:
z = np.zeros((3, 4), dtype=int)
z

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
z = np.zeros((2, 5, 3), dtype=int)
z

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
o = np.ones((4, 5), dtype=int)
o

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
f = np.full((2, 4), 9)
f

array([[9, 9, 9, 9],
       [9, 9, 9, 9]])

In [ ]:
a = np.arange(2, 21, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
l = np.linspace(1, 2, 10)
l

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [ ]:
l = np.linspace(2, 20, 10)
l

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [ ]:
rr = np.random.random((5, 4)) # Gives random numbers between 0 and 1
rr

array([[0.3549302 , 0.81416349, 0.29764186, 0.54461432],
       [0.96308222, 0.18339548, 0.72799734, 0.73324006],
       [0.04613998, 0.96958639, 0.37054354, 0.70694424],
       [0.2739307 , 0.24904506, 0.30497238, 0.13885199],
       [0.97511485, 0.0084119 , 0.8944718 , 0.35420418]])

In [ ]:
ri = np.random.randint(4, 10, (3,9))
ri

array([[8, 7, 6, 6, 8, 6, 7, 9, 5],
       [5, 9, 8, 4, 4, 5, 4, 9, 8],
       [4, 4, 7, 8, 6, 7, 9, 4, 8]])

In [ ]:
np.random.seed(38)
ri = np.random.randint(4, 10, (3,9))
ri

array([[5, 7, 9, 7, 8, 8, 6, 5, 5],
       [8, 4, 6, 5, 9, 9, 8, 7, 5],
       [6, 9, 9, 9, 5, 4, 6, 7, 7]])

In [ ]:
e = np.eye(5, dtype=int)
e

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# 6) Array Indexing


In [ ]:
import numpy as np

In [ ]:
np.random.seed(45)
arr1 = np.random.randint(10, size=10)
arr1

array([3, 0, 5, 3, 4, 9, 8, 1, 5, 9])

In [ ]:
arr1[0], arr1[1], arr1[2]

(3, 0, 5)

In [ ]:
arr1[-1], arr1[-2], arr1[-3]

(9, 5, 1)

In [ ]:
arr1[-1] = 403

In [ ]:
arr1

array([  3,   0,   5,   3,   4,   9,   8,   1,   5, 403])

In [ ]:
arr2 = np.random.randint(10, size=(3, 5)) # 3 rows | 5 columns
arr2

array([[6, 8, 7, 8, 5],
       [2, 8, 1, 6, 4],
       [8, 4, 6, 4, 9]])

In [ ]:
arr2[0]

array([6, 8, 7, 8, 5])

In [ ]:
arr2[0, 0]

6

In [ ]:
arr2[0, 0], arr2[1, 1], arr2[2, 2]

(6, 8, 6)

In [ ]:
arr2[1, 2]

1

In [ ]:
arr2[-1, -1]

9

In [ ]:
arr2[-2, -4]

8

In [ ]:
arr2[-2, -4] = 987
arr2

array([[  6,   8,   7,   8,   5],
       [  2, 987,   1,   6,   4],
       [  8,   4,   6,   4,   9]])

In [ ]:
arr3 = np.random.randint(10, size=(2, 3, 4))
arr3

array([[[1, 6, 8, 8],
        [1, 6, 0, 4],
        [9, 8, 0, 9]],

       [[2, 6, 7, 0],
        [0, 2, 9, 2],
        [6, 0, 9, 6]]])

In [ ]:
arr3[1, 1, 3]

2

In [ ]:
arr3[-2, 1]

array([1, 6, 0, 4])

In [ ]:
arr3[1]

array([[2, 6, 7, 0],
       [0, 2, 9, 2],
       [6, 0, 9, 6]])

In [ ]:
arr3[0] = 0

In [ ]:
arr3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[2, 6, 7, 0],
        [0, 2, 9, 2],
        [6, 0, 9, 6]]])

# 7) Array Slicing

In [ ]:
import numpy as np

In [ ]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr4[4: 8]

array([4, 5, 6, 7])

In [ ]:
arr4[1: 10: 2]

array([1, 3, 5, 7, 9])

In [ ]:
arr4[-4: -1]

array([6, 7, 8])

In [ ]:
np.random.seed(67)
arr5 = np.random.randint(1, 10, (3, 4))
arr5

array([[4, 6, 6, 8],
       [4, 7, 4, 8],
       [9, 6, 4, 7]])

In [ ]:
arr5[1:2]

array([[4, 7, 4, 8]])

In [ ]:
arr5[0:2, 1:3]

array([[6, 6],
       [7, 4]])

In [ ]:
arr5[-3:, 1:-1]

array([[6, 6],
       [7, 4],
       [6, 4]])

In [ ]:
arr6 = np.random.randint(1, 10, (2, 3, 4))
arr6

array([[[5, 8, 2, 4],
        [8, 9, 8, 3],
        [6, 6, 4, 3]],

       [[7, 7, 5, 9],
        [4, 2, 5, 9],
        [3, 8, 1, 8]]])

# 8) Array reshaping

In [ ]:
arr7 = np.arange(1, 10)
arr7

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr7.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr7.reshape(9, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
arr8 = np.arange(1, 21)
arr8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr8.reshape(5, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
arr8.reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr8.reshape(2, 5, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

# 9) Array Concatenation and Splitting

## Concatenation

In [ ]:
a1 = np.arange(1, 5)
a2 = np.arange(5, 9)
a1, a2

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [ ]:
np.concatenate([a1, a2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a3 = np.arange(1, 10).reshape(3, 3)
a4 = np.arange(10, 19).reshape(3, 3)
a3, a4

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]))

In [ ]:
np.concatenate([a3, a4]) # concatenates by rows

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.concatenate([a3, a4], axis=1) # concatenates by columns

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [ ]:
np.vstack([a3, a4])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.hstack([a3, a4])

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

## Splitting

In [1]:
import numpy as np

In [2]:
a5 = np.arange(1, 10)
a5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.split(a5, [4])

[array([1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
np.split(a5, [3, 5, 7])

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [6]:
a6 = np.arange(1, 21).reshape(5, 4)
a6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [7]:
np.split(a6, [2])

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])]

In [8]:
np.split(a6, [2], axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20]])]

In [ ]:
np.vsplit(a6, [3])

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]])]

In [ ]:
np.hsplit(a6, [2])

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20]])]

# 10) Universal NumPy Functions

## Arithmetic Operations

In [ ]:
import numpy as np
arr1 = np.arange(1, 11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.add(arr1, 5)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np.subtract(arr1, 2)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
np.multiply(arr1, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np.divide(arr1, 100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [ ]:
np.floor_divide(arr1, 4)

array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2])

In [ ]:
np.power(arr1, 2)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
np.mod(arr1, 2)

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

## Aggregate Operations

In [9]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2

array([1, 2, 3, 4, 5])

In [10]:
np.mean(arr2)

3.0

In [11]:
np.median(arr2)

3.0

In [ ]:
np.std(arr2)

1.4142135623730951

In [ ]:
np.var(arr2)

2.0

In [ ]:
np.min(arr2)

1

In [ ]:
np.max(arr2)

5

## Comparison Operations

In [13]:
import numpy as np
a1 = np.array([1, 2, 3, 4])
a2 = np.array([1, 0, 3, 7])
a1, a2

(array([1, 2, 3, 4]), array([1, 0, 3, 7]))

In [14]:
np.equal(a1, a2)

array([ True, False,  True, False])

In [15]:
np.less(a1, a2)

array([False, False, False,  True])

In [16]:
np.less_equal(a1, a2)

array([ True, False,  True,  True])

In [17]:
np.greater(a1, a2)

array([False,  True, False, False])

In [18]:
np.greater_equal(a1, a2)

array([ True,  True,  True, False])

In [19]:
np.not_equal(a1, a2)

array([False,  True, False,  True])

# What's next?

### Start learning **Pandas**.